- name: Create prometheus service unit
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service

- name: Starts prometheus service
  systemd:
    state: started
    enabled: true
    daemon_reload: true
    name: prometheus