- name: Create sonarqube service unit
  template:
    src: sonarqube.service.j2
    dest: /etc/systemd/system/sonarqube.service

- name: Starts sonarqube service
  systemd:
    state: restarted
    enabled: true
    daemon_reload: true
    name: sonarqube