- name: Install GPG package
  apt:
    name: gnupg
    state: present 

- name: Add mongodb key
  ansible.builtin.apt_key:
    url: "https://www.mongodb.org/static/pgp/server-6.0.asc"
    keyring: /usr/share/keyrings/mongodb-archive-keyring.gpg
    state: present

- name: Add repo
  ansible.builtin.apt_repository:
    repo: "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-archive-keyring.gpg ] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/6.0 multiverse"
    state: present
    update_cache: true

- name: Install Mongo DB
  apt:
    name: mongodb-org
    state: present