---
- hosts: kubernetes
  tasks:
    - name: Install kubeadm
      package:
        name: kubeadm
        state: latest
    - name: Install kubelet
      package:
        name: kubelet
        state: latest
    - name: Install kubectl
      package:
        name: kubectl
        state: latest
