---
# @description: Creates kubernetes master servers using CRI-O engine
- hosts: kubernetes_master
  become: true
  vars:
    crio_version: 1.18
    kube_version: 1.23.6-00
  roles:
    - cri-o
    - kubernetes
    - argo-cd