---

- name: Check for buster backports repository
  ansible.builtin.apt_repository:
    repo: deb http://deb.debian.org/debian buster-backports main
    state: present
    update_cache: false


- name: Check for libcontainers repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/libcontainers-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/x{{ ansible_distribution }}_{{ ansible_distribution_version }}/ /"
    state: present
    update_cache: false
  register: add_libcontainers_repo

- name: Check for libcontainers / CRI-O repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/libcontainers-crio-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ crio_version }}/x{{ ansible_distribution }}_{{ ansible_distribution_version }}/ /"
    state: present
    update_cache: false
  register: add_libcontainers_crio_repo
    
- name: Add keys for libcontainers repository
  ansible.builtin.apt_key:
    url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/x{{ ansible_distribution }}_{{ ansible_distribution_version }}/Release.key"
    keyring: /usr/share/keyrings/libcontainers-archive-keyring.gpg
    state: present

- name: Add keys for libcontainers / CRI-O repository
  ansible.builtin.apt_key:
    url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ crio_version }}/x{{ ansible_distribution }}_{{ ansible_distribution_version }}/Release.key"
    keyring: /usr/share/keyrings/libcontainers-crio-archive-keyring.gpg
    state: present
 
- name: Add buster backports GPG key 1
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 04EE7237B7D453EC
    state: present

- name: Add buster backports GPG key 2
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 648ACFD622F3D138
    state: present

- name: Update cache
  apt:
    update_cache: true