---
- name: Copy calico files to remote host
  copy:
    source: ./files/calico.yaml
    dest: /home/ansible/calico.yml

- name: Apply calico on kubernetes
  shell: kubectl apply -f /home/ansible/calico.yml