---
- name: Install kubeadm
  package:
    name: kubeadm=1.23.6-00
    state: present
    allow_downgrade: yes
    update_cache: true

- name: Install kubelet
  package:
    name: kubelet=1.23.6-00
    state: present
    allow_downgrade: yes
    update_cache: true

- name: Install kubectl
  package:
    name: kubectl=1.23.6-00
    state: present
    allow_downgrade: yes
    update_cache: true