---
- name: Install kubeadm
  package:
    name: kubeadm
    state: latest
    update_cache: true

- name: Install kubelet
  package:
    name: kubelet
    state: latest
    update_cache: true

- name: Install kubectl
  package:
    name: kubectl
    state: latest
    update_cache: true