---
- name: Install kubeadm
  package:
    name: kubeadm={{ kube_version }}
    state: present
    allow_downgrade: yes
    update_cache: true

- name: Install kubelet
  package:
    name: kubelet={{ kube_version }}
    state: present
    allow_downgrade: yes
    update_cache: true

- name: Install kubectl
  package:
    name: kubectl={{ kube_version }}
    state: present
    allow_downgrade: yes
    update_cache: true