- name: Get master node token
  shell: "kubeadm token create --print-join-command --ttl 1m --description \"Joining token for node {{ ansible_facts.hostname }}\""
  environment: 
    KUBECONFIG: /etc/kubernetes/admin.conf
  delegate_to: "{{ master_node }}"
  register: k8s_join_token

- name: Join master node
  shell: "{{ k8s_join_token.stdout }}"