---

- name: Copy kubeadm config file to remote host
  template:
    src: kubeadm-config.yaml.j2
    dest: /home/ansible/kubeadm-config.yaml

- name: Init Kubeadm
  become: true
  shell: |
    kubeadm init \
    --config=/home/ansible/kubeadm-config.yaml \
    --upload-certs
