---
- name: Load modprobe overlay
  community.general.modprobe:
    name: overlay
    state: present

- name: Load modprobe br_netfilter
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Configure net.ipv4.ip_forward on sysctl
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: true

- name: Configure net.bridge.bridge-nf-call-iptables on sysctl
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present
    reload: true

- name: Configure net.bridge.bridge-nf-call-ip6tables on sysctl
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: 1
    state: present
    reload: true