- name: Download Prometheus binary
  get_url:
    url: "{{ prometheus_download_url }}"
    dest: "/home/prometheus/prometheus.tar.gz"

- name: Unarchive Prometheus binary
  unarchive:
    src: "/home/prometheus/prometheus.tar.gz"
    dest: "/home/prometheus/"
    owner: prometheus
    group: prometheus
    remote_src: yes