---
- hosts: kubernetes
  become: true

  tasks:

    - name: Load modprobe overlay
      community.general.modprobe:
        name: overlay
        state: present

    - name: Load modprobe br_netfilter
      community.general.modprobe:
        name: br_netfilter
        state: present

    - name: Configure net.ipv4.ip_forward on sysctl
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        reload: true

    - name: Configure net.bridge.bridge-nf-call-iptables on sysctl
      ansible.posix.sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present
        reload: true

    - name: Configure net.bridge.bridge-nf-call-ip6tables on sysctl
      ansible.posix.sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: 1
        state: present
        reload: true
   
    - name: Copy kubelet config file
      copy:
        src: ./assets/kubelet.conf
        dest: /etc/default/kubelet

    - name: Install software-properties-common package
      package:
        name: software-properties-common
        state: latest
    
    - name: Check for Kubernetes archive
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
        state: present
        update_cache: false

    - name: Add keys for kubernetes archive
      ansible.builtin.apt_key:
        url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
        keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg

    - name: Install kubeadm
      package:
        name: kubeadm
        state: latest
        update_cache: true
    
    - name: Install kubelet
      package:
        name: kubelet
        state: latest
        update_cache: true
    
    - name: Install kubectl
      package:
        name: kubectl
        state: latest
        update_cache: true
