- name: Create node exporter service unit
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: Starts node exporter service
  systemd:
    state: started
    enabled: true
    daemon_reload: true
    name: node_exporter