- name: Get disk state
  shell: free -h

- name: Disable SWAP
  shell: swapoff -a

- name: Disable SWAP in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Reboot system
  ansible.builtin.reboot:
